# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/lge/judyln-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter judyln g710n g710ulm,$(TARGET_DEVICE)),)

endif
